version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
     - "5672:5672"
     - "15672:15672"
  catalogDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55W0rd"
    ports:
     - "1453:1433"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      DefaultHost: 'catalogDb'
    ports:
     - "8080:80"
    depends_on:
     - catalogDb
     - rabbitmq

  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Services/Stock/Stock.API/Stock.API/Dockerfile
    depends_on:
     - rabbitmq


  shipment.api:
    image: ${DOCKER_REGISTRY-}shipmentapi
    build:
      context: .
      dockerfile: Services/Shipment/Shipment.API/Shipment.API/Dockerfile
    depends_on:
     - rabbitmq


  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Payment.API/Dockerfile
    depends_on:
     - rabbitmq


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Order.API/Dockerfile
    depends_on:
     - rabbitmq


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Basket.API/Dockerfile
    depends_on:
     - rabbitmq